# Update with the following command
#   conda skeleton pypi pyomo
{% set version = "5.4.3" %}

package:
  name: pyomo
  version: {{ version }}

source: # pypi md5
  fn: Pyomo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyomo/Pyomo-{{ version }}.tar.gz
  md5: 31037be9ebf16beea5678a6f1c3df421

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - runbenders=pyomo.pysp.benders:Benders_main
    - evaluate_xhat=pyomo.pysp.evaluate_xhat:EvaluateXhat_main
    - runph=pyomo.pysp.phinit:PH_main
    - runef=pyomo.pysp.ef_writer_script:main
    - phsolverserver=pyomo.pysp.phsolverserver:main
    - scenariotreeserver=pyomo.pysp.scenariotree.server_pyro:main
    - computeconf=pyomo.pysp.computeconf:main
    - results_schema=pyomo.scripting.commands:results_schema
    - pyro_mip_server=pyomo.scripting.pyro_mip_server:main
    - test.pyomo=pyomo.scripting.runtests:runPyomoTests
    - pyomo=pyomo.scripting.pyomo_main:main
    - pyomo_ns=pyomo.scripting.commands:pyomo_ns
    - pyomo_nsc=pyomo.scripting.commands:pyomo_nsc
    - kill_pyro_mip_servers=pyomo.scripting.commands:kill_pyro_mip_servers
    - launch_pyro_mip_servers=pyomo.scripting.commands:launch_pyro_mip_servers
    - readsol=pyomo.scripting.commands:readsol
    - ossolverservice=pyomo.scripting.commands:OSSolverService
    - pyomo_python=pyomo.scripting.commands:pyomo_python
    - pyomo_old=pyomo.scripting.pyomo_command:main
    - get_pyomo_extras=scripts.get_pyomo_extras:main

requirements:
  build:
    - python
    - setuptools
    - pyutilib >=5.6
    - appdirs
    - ply
    - six >=1.4

  run:
    - python
    - setuptools
    - pyutilib >=5.6
    - appdirs
    - ply
    - six >=1.4

test:
  imports: # Note that there may be new imports
    - pyomo
    - pyomo.bilevel
    - pyomo.bilevel.plugins
    - pyomo.bilevel.tests
    - pyomo.checker
    - pyomo.checker.plugins
    - pyomo.checker.plugins.checkers
    - pyomo.checker.plugins.checkers.model
    - pyomo.checker.plugins.checkers.py3k
    - pyomo.checker.plugins.checkers.sample
    - pyomo.checker.tests
    - pyomo.contrib
    - pyomo.core
    - pyomo.core.base
    - pyomo.core.beta
    - pyomo.core.data
    - pyomo.core.kernel
    - pyomo.core.plugins
    - pyomo.core.plugins.data
    - pyomo.core.plugins.transform
    - pyomo.core.preprocess
    - pyomo.core.tests
    - pyomo.core.tests.data
    - pyomo.core.tests.diet
    - pyomo.core.tests.examples
    - pyomo.core.tests.transform
    - pyomo.core.tests.unit
    - pyomo.dae.plugins
    - pyomo.dae.tests
    - pyomo.environ
    - pyomo.environ.tests
    - pyomo.gdp
    - pyomo.gdp.plugins
    - pyomo.gdp.tests
    - pyomo.mpec
    - pyomo.mpec.plugins
    - pyomo.mpec.tests
    - pyomo.neos
    - pyomo.neos.plugins
    - pyomo.neos.tests
    - pyomo.opt
    - pyomo.opt.base
    - pyomo.opt.blackbox
    - pyomo.opt.parallel
    - pyomo.opt.plugins
    - pyomo.opt.problem
    - pyomo.opt.results
    - pyomo.opt.solver
    - pyomo.opt.testing
    - pyomo.opt.tests
    - pyomo.opt.tests.base
    - pyomo.opt.tests.blackbox
    - pyomo.opt.tests.solver
    - pyomo.pysp
    - pyomo.pysp.plugins
    - pyomo.pysp.scenariotree
    - pyomo.pysp.solvers
    - pyomo.pysp.tests
    - pyomo.pysp.tests.benders
    - pyomo.pysp.tests.evalxhat
    - pyomo.pysp.tests.examples
    - pyomo.pysp.tests.scenariotreemanager
    - pyomo.pysp.tests.unit
    - pyomo.pysp.util
    - pyomo.repn
    - pyomo.repn.beta
    - pyomo.repn.plugins
    - pyomo.repn.plugins.ampl
    - pyomo.repn.tests
    - pyomo.repn.tests.ampl
    - pyomo.repn.tests.cpxlp
    - pyomo.repn.tests.mps
    - pyomo.scripting
    - pyomo.scripting.plugins
    - pyomo.scripting.tests
    - pyomo.solvers
    - pyomo.solvers.plugins
    - pyomo.solvers.plugins.converter
    - pyomo.solvers.plugins.smanager
    - pyomo.solvers.plugins.solvers
    - pyomo.solvers.plugins.testdriver
    - pyomo.solvers.tests
    - pyomo.solvers.tests.checks
    - pyomo.solvers.tests.core
    - pyomo.solvers.tests.core.plugins
    - pyomo.solvers.tests.mip
    - pyomo.solvers.tests.models
    - pyomo.solvers.tests.piecewise_linear
    - pyomo.util
    - pyomo.util.tests
    - pyomo.version
    - pyomo.version.tests

  commands:
    - runbenders --help
    - evaluate_xhat --help
    - runph --help
    - runef --help
    - phsolverserver --help
    - scenariotreeserver --help
    - computeconf --help
    - test.pyomo --help
    - pyomo --help

about:
  home: http://pyomo.org
  license: "BSD 3-Clause"
  summary: 'Pyomo: Python Optimization Modeling Objects'
  license_family: BSD

extra:
  recipe-maintainers:
    - whart222
    - jsiirola
    - juanlu001
