# Update with the following command
#   conda skeleton pypi pyomo
{% set version = "6.1" %}

package:
  name: pyomo
  version: {{ version }}

source: # pypi md5
  fn: Pyomo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyomo/Pyomo-{{ version }}.tar.gz
  sha256: 7d087b186a43b2ffd032bc4db87cdbcf2fdc187607211f3e6cdc0f54b6f516f4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyomo=pyomo.scripting.pyomo_main:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - cython

  run:
    - python
    - setuptools
    - ply

test:
  imports: # Note that there may be new imports
    - pyomo
    - pyomo.bilevel
    - pyomo.bilevel.plugins
    - pyomo.checker
    - pyomo.checker.plugins
    - pyomo.checker.plugins.checkers
    - pyomo.checker.plugins.checkers.model
    - pyomo.checker.plugins.checkers.py3k
    - pyomo.checker.plugins.checkers.sample
    - pyomo.common
    - pyomo.common.collections
    - pyomo.contrib
    - pyomo.contrib.appsi
    - pyomo.contrib.appsi.cmodel
    - pyomo.contrib.appsi.examples
    - pyomo.contrib.appsi.solvers
    - pyomo.contrib.appsi.utils
    - pyomo.contrib.appsi.writers
    - pyomo.contrib.benders
    - pyomo.contrib.community_detection
    - pyomo.contrib.example
    - pyomo.contrib.example.plugins
    - pyomo.contrib.fbbt
    - pyomo.contrib.fme
    - pyomo.contrib.gdp_bounds
    - pyomo.contrib.gdpbb
    - pyomo.contrib.gdpopt
    - pyomo.contrib.incidence_analysis
    - pyomo.contrib.interior_point
    - pyomo.contrib.interior_point.linalg
    - pyomo.contrib.mcpp
    - pyomo.contrib.mindtpy
    - pyomo.contrib.multistart
    - pyomo.contrib.parmest
    - pyomo.contrib.parmest.examples
    - pyomo.contrib.parmest.examples.reactor_design
    - pyomo.contrib.parmest.examples.rooney_biegler
    - pyomo.contrib.parmest.examples.semibatch
    - pyomo.contrib.preprocessing
    - pyomo.contrib.preprocessing.plugins
    - pyomo.contrib.pynumero
    - pyomo.contrib.pynumero.algorithms
    - pyomo.contrib.pynumero.algorithms.solvers
    - pyomo.contrib.pynumero.examples
    - pyomo.contrib.pynumero.examples.callback
    - pyomo.contrib.pynumero.examples.external_grey_box
    - pyomo.contrib.pynumero.examples.external_grey_box.param_est
    - pyomo.contrib.pynumero.examples.external_grey_box.react_example
    - pyomo.contrib.pynumero.interfaces
    - pyomo.contrib.pynumero.linalg
    - pyomo.contrib.pynumero.sparse
    - pyomo.contrib.pyros
    - pyomo.contrib.satsolver
    - pyomo.contrib.sensitivity_toolbox
    - pyomo.contrib.sensitivity_toolbox.examples
    - pyomo.contrib.trustregion
    - pyomo.contrib.viewer
    - pyomo.core
    - pyomo.core.base
    - pyomo.core.beta
    - pyomo.core.expr
    - pyomo.core.expr.calculus
    - pyomo.core.kernel
    - pyomo.core.kernel.piecewise_library
    - pyomo.core.plugins
    - pyomo.core.plugins.transform
    - pyomo.dae
    - pyomo.dae.plugins
    - pyomo.dataportal
    - pyomo.dataportal.plugins
    - pyomo.duality
    - pyomo.environ
    - pyomo.gdp
    - pyomo.gdp.plugins
    - pyomo.kernel
    - pyomo.mpec
    - pyomo.mpec.plugins
    - pyomo.neos
    - pyomo.neos.plugins
    - pyomo.network
    - pyomo.network.plugins
    - pyomo.opt
    - pyomo.opt.base
    - pyomo.opt.parallel
    - pyomo.opt.plugins
    - pyomo.opt.problem
    - pyomo.opt.results
    - pyomo.opt.solver
    - pyomo.opt.testing
    - pyomo.repn
    - pyomo.repn.beta
    - pyomo.repn.plugins
    - pyomo.repn.plugins.ampl
    - pyomo.scripting
    - pyomo.scripting.plugins
    - pyomo.solvers
    - pyomo.solvers.plugins
    - pyomo.solvers.plugins.converter
    - pyomo.solvers.plugins.solvers
    - pyomo.util
    - pyomo.version

  commands:
    - pyomo --help

about:
  home: http://pyomo.org
  license: "BSD-3-Clause"
  license_file: '{{ environ["RECIPE_DIR"] }}/Pyomo-LICENSE.txt'
  summary: 'Pyomo: Python Optimization Modeling Objects'
  license_family: BSD

extra:
  recipe-maintainers:
    - whart222
    - jsiirola
    - blnicho
