# Update with the following command
#   conda skeleton pypi pyomo
{% set version = "5.6.6" %}

package:
  name: pyomo
  version: {{ version }}

source: # pypi md5
  fn: Pyomo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/Pyomo/Pyomo-{{ version }}.tar.gz
  sha256: 813e14a604b9d3ac63bdd0880c07f5f4e1b8f0a8a10345f1b42bee762219c001

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - runbenders=pyomo.pysp.benders:Benders_main
    - evaluate_xhat=pyomo.pysp.evaluate_xhat:EvaluateXhat_main
    - runph=pyomo.pysp.phinit:PH_main
    - runef=pyomo.pysp.ef_writer_script:main
    - phsolverserver=pyomo.pysp.phsolverserver:main
    - scenariotreeserver=pyomo.pysp.scenariotree.server_pyro:main
    - computeconf=pyomo.pysp.computeconf:main
    - results_schema=pyomo.scripting.commands:results_schema
    - pyro_mip_server=pyomo.scripting.pyro_mip_server:main
    - test.pyomo=pyomo.scripting.runtests:runPyomoTests
    - pyomo=pyomo.scripting.pyomo_main:main
    - pyomo_ns=pyomo.scripting.commands:pyomo_ns
    - pyomo_nsc=pyomo.scripting.commands:pyomo_nsc
    - kill_pyro_mip_servers=pyomo.scripting.commands:kill_pyro_mip_servers
    - launch_pyro_mip_servers=pyomo.scripting.commands:launch_pyro_mip_servers
    - readsol=pyomo.scripting.commands:readsol
    - ossolverservice=pyomo.scripting.commands:OSSolverService
    - pyomo_python=pyomo.scripting.commands:pyomo_python
    - pyomo_old=pyomo.scripting.pyomo_command:main

requirements:
  build:
    - python
    - setuptools
    - pyutilib >=5.7.1
    - appdirs
    - ply
    - six >=1.4

  run:
    - python
    - setuptools
    - pyutilib >=5.7.1
    - appdirs
    - ply
    - six >=1.4

test:
  imports: # Note that there may be new imports
    - pyomo
    - pyomo.bilevel
    - pyomo.bilevel.plugins
    - pyomo.checker
    - pyomo.checker.plugins
    - pyomo.checker.plugins.checkers
    - pyomo.checker.plugins.checkers.model
    - pyomo.checker.plugins.checkers.py3k
    - pyomo.checker.plugins.checkers.sample
    - pyomo.common
    - pyomo.contrib
    - pyomo.contrib.benders
    - pyomo.contrib.derivatives
    - pyomo.contrib.example
    - pyomo.contrib.example.plugins
    - pyomo.contrib.fbbt
    - pyomo.contrib.gdpbb
    - pyomo.contrib.gdp_bounds
    - pyomo.contrib.gdpopt
    - pyomo.contrib.mcpp
    - pyomo.contrib.mindtpy
    - pyomo.contrib.multistart
    - pyomo.contrib.parmest
    - pyomo.contrib.parmest.examples
    - pyomo.contrib.parmest.examples.reactor_design
    - pyomo.contrib.parmest.examples.rooney_biegler
    - pyomo.contrib.parmest.examples.semibatch
    - pyomo.contrib.preprocessing
    - pyomo.contrib.preprocessing.plugins
    - pyomo.contrib.pynumero
    - pyomo.contrib.pynumero.algorithms
    - pyomo.contrib.pynumero.examples
    - pyomo.contrib.pynumero.extensions
    - pyomo.contrib.pynumero.interfaces
    - pyomo.contrib.pynumero.linalg
    - pyomo.contrib.pynumero.sparse
    - pyomo.contrib.satsolver
    - pyomo.contrib.sensitivity_toolbox
    - pyomo.contrib.sensitivity_toolbox.examples
    - pyomo.contrib.trustregion
    - pyomo.contrib.viewer
    - pyomo.core
    - pyomo.core.base
    - pyomo.core.beta
    - pyomo.core.expr
    - pyomo.core.kernel
    - pyomo.core.kernel.piecewise_library
    - pyomo.core.plugins
    - pyomo.core.plugins.transform
    - pyomo.core.preprocess
    - pyomo.dae
    - pyomo.dae.plugins
    - pyomo.dataportal
    - pyomo.dataportal.plugins
    - pyomo.duality
    - pyomo.environ
    - pyomo.gdp
    - pyomo.gdp.plugins
    - pyomo.kernel
    - pyomo.mpec
    - pyomo.mpec.plugins
    - pyomo.neos
    - pyomo.neos.plugins
    - pyomo.network
    - pyomo.network.plugins
    - pyomo.opt
    - pyomo.opt.base
    - pyomo.opt.blackbox
    - pyomo.opt.parallel
    - pyomo.opt.plugins
    - pyomo.opt.problem
    - pyomo.opt.results
    - pyomo.opt.solver
    - pyomo.opt.testing
    - pyomo.pysp
    - pyomo.pysp.convert
    - pyomo.pysp.plugins
    - pyomo.pysp.scenariotree
    - pyomo.pysp.solvers
    - pyomo.pysp.util
    - pyomo.repn
    - pyomo.repn.beta
    - pyomo.repn.plugins
    - pyomo.repn.plugins.ampl
    - pyomo.scripting
    - pyomo.scripting.plugins
    - pyomo.solvers
    - pyomo.solvers.plugins
    - pyomo.solvers.plugins.converter
    - pyomo.solvers.plugins.smanager
    - pyomo.solvers.plugins.solvers
    - pyomo.solvers.plugins.testdriver
    - pyomo.util
    - pyomo.version

  commands:
    - runbenders --help
    - evaluate_xhat --help
    - runph --help
    - runef --help
    - phsolverserver --help
    - scenariotreeserver --help
    - computeconf --help
    - test.pyomo --help
    - pyomo --help

about:
  home: http://pyomo.org
  license: "BSD 3-Clause"
  license_file: LICENSE.txt
  summary: 'Pyomo: Python Optimization Modeling Objects'
  license_family: BSD

extra:
  recipe-maintainers:
    - whart222
    - jsiirola
    - juanlu001
    - blnicho
